import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import { UserProps } from './api/users'

// const fetcher = (...args: any[]) => fetch(...args).then((res) => res.json())
const fetcher = (url: URL) => fetch(url).then(r => r.json())


const UserInfo = (props: UserProps) => {
  const {id, firstName, lastName} = props
  return (
    <p key={id}>Name: {firstName} {lastName + '.'}</p>
  )
}

const Users = () => {
  const apiPath = '/api/users'
  const {data, error} = useSWR(apiPath, fetcher)
  if (error) return <div>failed to load users {apiPath}</div>
  if (!data) return <div>loading...</div>
  const users: UserProps[] = data.users
  return (
    <div>
      <h2>Users</h2>
      {users.map(u => <UserInfo key={u.id} {...u} />)}
    </div>
  )

}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Users />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
